version: "3.8"

services:
  ingest:
    build: ./ingest
    container_name: pricebyte-ingest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_pFec60LRKvsf@ep-fragrant-block-a7lnk03h-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    ports:
      - "8000:8000"
    networks:
      - scrapers-network

  scrapers:
    build: ./scrapers
    container_name: pricebyte-scrapers
    restart: "no"
    environment:
      RAPIDAPI_KEY: ${RAPIDAPI_KEY}
      DATABASE_URL: postgresql://neondb_owner:npg_pFec60LRKvsf@ep-fragrant-block-a7lnk03h-pooler.ap-southeast-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    networks:
      - scrapers-network
    depends_on:
      - ingest

networks:
  scrapers-network:
    driver: bridge